name: Deploy to Azure Web App

on:
  workflow_run:
    workflows: ["Build ASP.Net Core app"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest

    permissions:
      id-token: write # Requis pour utiliser un jeton OIDC pour se connecter à Azure.

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Azure login
        uses: azure/login@v2
        with:
          auth-type: 'IDENTITY'
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'LinkUpWebAppTest'
          slot-name: 'production'
          package: .
